#!/bin/sh
echo "By http://www.NoobsLab.com
"
echo "Settings GTK themes, Docky theme, and Icons for you."
sleep 3
echo ".
"
gsettings set org.gnome.desktop.interface icon-theme 'MBuntu-OS-Y';echo "..
";sleep 0.5;gsettings set org.compiz.unityshell:/org/compiz/profiles/unity/plugins/unityshell/ panel-opacity 0.5;echo "...
";sleep 0.5;gsettings set org.gnome.desktop.interface gtk-theme 'MBuntu-Y';echo "....
";sleep 0.5;gsettings set org.gnome.desktop.wm.preferences theme 'MBuntu-Y';echo ".....
";sleep 0.5;gsettings set com.canonical.desktop.interface scrollbar-mode normal;echo "......
";sleep 0.5;gsettings set org.compiz.unityshell:/org/compiz/profiles/unity/plugins/unityshell/ launcher-hide-mode 1;echo ".......
";sleep 0.5;pkill docky;gconftool-2 -s -t string /apps/docky-2/Docky/Services/ThemeService/Theme MBuntu-Y-A;echo "........
";sleep 0.5;gconftool-2 -s -t string /apps/docky-2/Docky/Interface/DockPreferences/Dock1/Autohide Intellihide;echo ".........
";sleep 0.5;gconftool-2 -s -t string /apps/docky-2/Docky/Services/ThemeService/Theme MBuntu-Y-A;gconftool-2 -s -t string /apps/docky-2/Docky/Interface/DockPreferences/Dock1/Autohide Intellihide;gconftool-2 --type list --list-type string --set /apps/docky-2/Docky/Interface/DockPreferences/Dock1/Launchers '[file:///usr/share/applications/nautilus.desktop,file:///usr/share/applications/slingscold.desktop,file:///usr/share/applications/nautilus-home.desktop,file:///usr/share/applications/vlc.desktop,file:///usr/share/applications/totem.desktop,file:///usr/share/applications/ubuntu-software-center.desktop,file:///usr/share/applications/firefox.desktop,file:///usr/share/applications/exo-web-browser.desktop,file:///usr/share/applications/gnome-terminal.desktop,file:///usr/share/applications/unity-control-center.desktop,file:///usr/share/applications/libreoffice-writer.desktop,file:///usr/share/applications/libreoffice-impress.desktop,file:///usr/share/applications/libreoffice-calc.desktop,file:///usr/share/applications/gedit.desktop,file:///usr/share/applications/cheese.desktop,file:///usr/share/applications/gnome-system-monitor.desktop,file:///usr/share/applications/yelp.desktop]'
echo "..........
";sleep 0.5;gconftool-2 --type list --list-type string --set /apps/docky-2/Docky/Interface/DockPreferences/Dock1/Plugins '[Trash]';echo "...........
";sleep 0.5;gconftool-2 -s -t boolean /apps/docky-2/Docky/Interface/DockPreferences/Dock1/ThreeDimensional false;echo "............
";sleep 0.5;gconftool-2 --type Boolean --set /apps/docky-2/Docky/Items/DockyItem/ShowDockyItem true;echo ".............
";sleep 0.5;wget -O $HOME/Pictures/mbuntu-default.jpg -q http://drive.noobslab.com/data/Mac-15.04/mbuntu-default.jpg;gsettings set org.gnome.desktop.background picture-uri file:///home/noobslab/Pictures/mbuntu-default.jpg;
(docky &) 2> /dev/null > /dev/null
echo "Setting up docky"
sleep 2
pkill docky;gconftool-2 -s -t string /apps/docky-2/Docky/Services/ThemeService/Theme MBuntu-Y-A;echo "........
";sleep 0.5;gconftool-2 -s -t string /apps/docky-2/Docky/Interface/DockPreferences/Dock1/Autohide Intellihide;echo ".........
";sleep 0.5;gconftool-2 -s -t string /apps/docky-2/Docky/Services/ThemeService/Theme MBuntu-Y-A;gconftool-2 -s -t string /apps/docky-2/Docky/Interface/DockPreferences/Dock1/Autohide Intellihide;gconftool-2 --type list --list-type string --set /apps/docky-2/Docky/Interface/DockPreferences/Dock1/Launchers '[file:///usr/share/applications/nautilus.desktop,file:///usr/share/applications/slingscold.desktop,file:///usr/share/applications/nautilus-home.desktop,file:///usr/share/applications/vlc.desktop,file:///usr/share/applications/totem.desktop,file:///usr/share/applications/ubuntu-software-center.desktop,file:///usr/share/applications/firefox.desktop,file:///usr/share/applications/exo-web-browser.desktop,file:///usr/share/applications/gnome-terminal.desktop,file:///usr/share/applications/unity-control-center.desktop,file:///usr/share/applications/libreoffice-writer.desktop,file:///usr/share/applications/libreoffice-impress.desktop,file:///usr/share/applications/libreoffice-calc.desktop,file:///usr/share/applications/gedit.desktop,file:///usr/share/applications/cheese.desktop,file:///usr/share/applications/gnome-system-monitor.desktop,file:///usr/share/applications/yelp.desktop]'
echo "..........
";sleep 0.5;gconftool-2 --type list --list-type string --set /apps/docky-2/Docky/Interface/DockPreferences/Dock1/Plugins '[Trash]';echo "...........
";sleep 0.5;gconftool-2 -s -t boolean /apps/docky-2/Docky/Interface/DockPreferences/Dock1/ThreeDimensional false;echo "............
";sleep 0.5;gconftool-2 --type Boolean --set /apps/docky-2/Docky/Items/DockyItem/ShowDockyItem true;echo ".............
";sleep 0.5;
(docky &) 2> /dev/null > /dev/null
sleep 4;
echo "Adjusting docky...."
pkill docky;gconftool-2 -s -t string /apps/docky-2/Docky/Services/ThemeService/Theme MBuntu-Y-A;echo "........
";sleep 0.5;gconftool-2 -s -t string /apps/docky-2/Docky/Interface/DockPreferences/Dock1/Autohide Intellihide;echo ".........
";sleep 0.5;gconftool-2 -s -t string /apps/docky-2/Docky/Services/ThemeService/Theme MBuntu-Y-A;gconftool-2 -s -t string /apps/docky-2/Docky/Interface/DockPreferences/Dock1/Autohide Intellihide;gconftool-2 --type list --list-type string --set /apps/docky-2/Docky/Interface/DockPreferences/Dock1/Launchers '[file:///usr/share/applications/nautilus.desktop,file:///usr/share/applications/slingscold.desktop,file:///usr/share/applications/nautilus-home.desktop,file:///usr/share/applications/vlc.desktop,file:///usr/share/applications/totem.desktop,file:///usr/share/applications/ubuntu-software-center.desktop,file:///usr/share/applications/firefox.desktop,file:///usr/share/applications/exo-web-browser.desktop,file:///usr/share/applications/gnome-terminal.desktop,file:///usr/share/applications/unity-control-center.desktop,file:///usr/share/applications/libreoffice-writer.desktop,file:///usr/share/applications/libreoffice-impress.desktop,file:///usr/share/applications/libreoffice-calc.desktop,file:///usr/share/applications/gedit.desktop,file:///usr/share/applications/cheese.desktop,file:///usr/share/applications/gnome-system-monitor.desktop,file:///usr/share/applications/yelp.desktop]'
echo "..........
";sleep 0.5;gconftool-2 --type list --list-type string --set /apps/docky-2/Docky/Interface/DockPreferences/Dock1/Plugins '[Trash]';echo "...........
";sleep 0.5;gconftool-2 -s -t boolean /apps/docky-2/Docky/Interface/DockPreferences/Dock1/ThreeDimensional false;echo "............
";sleep 0.5;gconftool-2 --type Boolean --set /apps/docky-2/Docky/Items/DockyItem/ShowDockyItem true;echo ".............
";sleep 0.5;
(docky &) 2> /dev/null > /dev/null
cd;rm config.sh 2> /dev/null
sleep 1
echo "All Done."
